export const data = [
  "Home Page",
  "Home Slider",
  "Agency",
  "Landing Wallet",
  "Landing ICO 1",
  "Landing ICO 2",
  "Landing ICO 3",
  "Landing ICO 5",
  "Mining Farm",
];
export const data2 = [
  "About",
  "Services",
  "Blog",
  "Blog Massonry",
  "Blog Post",
  "Pricinag Tables",
  "Typography",
  "404 page",
  "Widgets",
  "Contact",
  "Sign In",
  "Sign Up",
];
